# Generated by Django 5.1 on 2025-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ano_lanzamiento', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('clasificacion_edad', models.CharField(max_length=50)),
                ('duracion_minutos', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('idioma_original', models.CharField(max_length=50)),
            ],
        ),
    ]
