# Generated by Django 5.1 on 2025-11-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Netflix', '0002_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_lista', models.IntegerField()),
                ('fecha_adicion', models.DateField(auto_now_add=True)),
                ('orden_en_lista', models.IntegerField()),
                ('visto_en_lista', models.BooleanField(default=False)),
                ('notas_personales', models.TextField(blank=True, null=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_listas_favoritos', to='app_Netflix.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_favoritos', to='app_Netflix.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
